### ISSUE TITLE
Android 7

### ISSUE THREAD

**Issue by Ekky78** [theawless/EventLock#17] opened 2017-08-19 13:24 UTC
Hello. I have Android 7.1.1 and xposed for this android. I'm sorry that the module does not work. After restart, wants to restart and then shuts it down. Is there any update in the plan?

**Comment by theawless** [comment] 2017-08-20 10:39
I have not tested this application on Android 7.1.1. Which mobile do you have? Can you confirm if the lockscreen is stock AOSP?

**Comment by ralismark** [comment] 2017-10-10 11:25
Issue also happens for me.
Moto G (titan), Android 7.1.2, Lineage 14.1. Should be AOSP lock screen.

Stack trace says:
Caused by: android.view.InflateException: Binary XML file line #39: Binary XML file line #1: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class fragment
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

MODE_WORLD_READABLE is used in [SettingsFragment.java](https://github.com/theawless/EventLock/blob/ed283b961ca572c295a61ff919242a628912a800/app/src/main/java/com/gobbledygook/theawless/eventlock/app/SettingsFragment.java#L59). I think that's the only use of it.

**Comment by theawless** [comment] 2017-10-10 14:33
@ralismark thanks for pointing that out! I was using deprecated ways to share preferences with xposed :/ and now Android 7 doesn't support it anymore...

I'm super busy with college these days, I'll try to fix it whenever I get time.

**Comment by Ekky78** [comment] 2017-11-11 07:30
Hello. Any progress with the development of functionality for Nougat?

**Comment by theawless** [comment] 2017-11-12 08:11
@Ekky78 not yet... I'm guessing it will require lots of changes to the code. I will look into it in December.

**Comment by theawless** [comment] 2017-12-13 19:14
Hey! I have attempted to fix the nougat compatibility issue, but I do not own a nougat device. Can any of you help me with testing the update?

I attached the apk in this zip, can you run and verify if it works?
[eventlock.zip](https://github.com/theawless/EventLock/files/1556711/eventlock.zip)

**Comment by Ekky78** [comment] 2017-12-13 20:08
Yes. Perfect. The application will not shut down or fall after the restart, before the refresh fell when the reflash is loaded. otherwise it works. Good work. I think they can put it into circulation.

**Comment by theawless** [comment] 2017-12-14 17:31
Fixed in 83ba3ddb59ba2a2fb21b30c88ab03c3b3c4b9b64

**Closed as completed by theawless** 2017-12-14 17:31 UTC
Labels: bug
